### ISSUE TITLE
add augmentations info

### ISSUE THREAD

**Issue by navjot-nangia** [precision-sustainable-ag/Field-SegmentationTraining#35]
Add augmentation applied info in the unet_conf.yaml file for each trained model.

example:

```
batch_size: 32
epochs: 30
learning_rate: 0.0001
train_size: 4117
val_size: 1030

augmentation_applied:
  - solarize_200/255
  - color_jitter
  - random_apply_p=0.5
```

**Comment by mkutu** [comment]
something with a little more detail will help later one down the line an allows for more detailed and efficient fine tunning: 
```yaml
augmentations:
  solarize:
    probability: 0.5
    state: True
  color_jitter:
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.1
    probability: 0.5
    state: True
  horizontal_flip:
    state: True
    probability: 0.5
  vertical_flip:
    probability: 0.5
    state: True
```
Another [example](https://github.com/precision-sustainable-ag/SemiF-Segmentation/blob/develop/conf/augment/basic.yaml)
